services:
  web:
    container_name: web
    command: ["npm", "run", "client:dev", "--", "--", "--host"]
    build:
      target: base
      dockerfile: Dockerfile
      context: apps/client/
      additional_contexts:
        - monorepo-root=./
    volumes:
      - ./apps/client/:/home/node/app/apps/client/
      - /home/node/app/apps/client/node_modules/
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - shared-net
    depends_on:
      - server
    restart: unless-stopped

  server:
    container_name: server
    # see https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
    init: true
    build:
      target: base
      dockerfile: Dockerfile
      context: apps/server/
      additional_contexts:
        - monorepo-root=./
    command: ["npm", "run", "server:dev"]
    volumes:
      - ./apps/server/:/home/node/app/apps/server/
      - /home/node/app/apps/server/node_modules/
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - shared-net
    restart: unless-stopped

networks:
  shared-net:
    driver: bridge
