name: CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.20'

      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint --workspace=@pr-viewer/client
      
      - name: Lint
        run: npm run all:lint
      
      - name: Format check
        run: npm run all:format:check

      - name: Test
        run: npm run all:test

